baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Category Theorists'
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "archie"



[Params]
  mode = "dark"
  useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
